### Create a namespace
PUT localhost:8080/v1/namespaces/foo/qux
Authorization: ApiToken test

### List all values in namespace
GET localhost:8080/v1/namespaces/foo
Authorization: ApiToken test

### List all namespaces
GET localhost:8080/v1/namespaces
Authorization: ApiToken test

### Delete a namespace
DELETE localhost:8080/v1/namespaces/foo/bar
Authorization: ApiToken test
