### Set a kv
PUT http://localhost:8080/v1/kv/foo/bar/key2
Content-Type: application/json
Authorization: ApiToken test

{
  "value": "v3"
}

### Get a kv
GET http://localhost:8080/v1/kv/foo/bar/key2
Authorization: ApiToken test

### Delete a kv
DELETE localhost:8080/v1/kv/foo/bar/key2
Authorization: ApiToken test
