### Set a kv
PUT http://localhost:8080/v1/kv/foo/bar/key
Content-Type: application/json
Authorization: ApiToken test

{
  "value": "v2"
}

### Get a kv
GET http://localhost:8080/v1/kv/foo/bar/key
Authorization: ApiToken test
